"""Fix message table

Revision ID: 2f9de2060ea7
Revises: 789298074002
Create Date: 2026-06-23 14:54:24.669584

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2f9de2060ea7"
down_revision: Union[str, Sequence[str], None] = "789298074002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column("room_name", sa.String(length=30), nullable=False),
    )
    op.drop_constraint(
        op.f("messages_room_id_fkey"), "messages", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "messages", "rooms", ["room_name"], ["name"], ondelete="CASCADE"
    )
    op.drop_column("messages", "room_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column(
            "room_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.create_foreign_key(
        op.f("messages_room_id_fkey"),
        "messages",
        "rooms",
        ["room_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("messages", "room_name")
    # ### end Alembic commands ###
