"""Fix rooms table

Revision ID: 789298074002
Revises: 56f71801b4be
Create Date: 2026-06-22 23:25:11.313035

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "789298074002"
down_revision: Union[str, Sequence[str], None] = "56f71801b4be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rooms", sa.Column("name", sa.String(length=30), nullable=False)
    )
    op.drop_constraint(op.f("rooms_token_key"), "rooms", type_="unique")
    op.drop_constraint(op.f("rooms_username_key"), "rooms", type_="unique")
    op.create_unique_constraint(None, "rooms", ["name"])
    op.drop_column("rooms", "username")
    op.drop_column("rooms", "token")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rooms",
        sa.Column("token", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "rooms",
        sa.Column(
            "username",
            sa.VARCHAR(length=30),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "rooms", type_="unique")
    op.create_unique_constraint(
        op.f("rooms_username_key"),
        "rooms",
        ["username"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("rooms_token_key"),
        "rooms",
        ["token"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("rooms", "name")
    # ### end Alembic commands ###
